arm64: vdso32: Include types UAPI header
- Commit [1] removed the inclusion of the types UAPI header which caused an error with vdso32:

In file included from ../arch/arm64/kernel/vdso32/vgettimeofday.c:1:
../arch/arm64/kernel/vdso32/compiler.h:81:32: error: unknown type name 'u64'
   81 | static __always_inline notrace u64 arch_vdso_read_counter(void)
      |                                ^~~
../arch/arm64/kernel/vdso32/compiler.h: In function 'arch_vdso_read_counter':
../arch/arm64/kernel/vdso32/compiler.h:83:9: error: unknown type name 'u64'
   83 |         u64 res;
      |         ^~~

- Fix it by including the types UAPI header manually in arch/arm64/kernel/vdso32/compiler.h.

Change-Id: I5b40b33edc3e10d08525d7496ce723e2529eb3b9
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
Signed-off-by: Richard Raya <rdxzv.dev@gmail.com>
Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>