Revert "fs/exec: PIDTYPE_TGID->__PIDTYPE_TGID"
This reverts commit 2a0cd3604e804727490bdf11ec1d070e8dbfc78e.

Broke after 5.10 bpf changes
../fs/exec.c:1802:7: error: use of undeclared identifier '__PIDTYPE_TGID'; did you mean 'PIDTYPE_TGID'?
1 error generated.

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>