Revert "net: tcp: Implement bbrplus"
This reverts commit 22c1004be21c9804527f0e9524b6a3a7cc19d6a1.

Broke compilation after 5.10 bpf patches. CBA to fix

../net/ipv4/tcp_bbrplus.c:395:30: error: implicit declaration of function 'tcp_tso_autosize' [-Werror,-Wimplicit-function-declaration]
  395 |     bbr->tso_segs_goal = min(tcp_tso_autosize(sk, tp->mss_cache, min_segs),
      |                              ^
../net/ipv4/tcp_bbrplus.c:395:26: warning: comparison of distinct pointer types ('typeof (tcp_tso_autosize(sk, tp->mss_cache, min_segs)) *' (aka 'int *') and 'typeof (127U) *' (aka 'unsigned int *')) [-Wcompare-distinct-pointer-types]
  395 |     bbr->tso_segs_goal = min(tcp_tso_autosize(sk, tp->mss_cache, min_segs),
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  396 |                  0x7FU);
      |                  ~~~~~~
../include/linux/kernel.h:847:19: note: expanded from macro 'min'
  847 | #define min(x, y)       __careful_cmp(x, y, <)
      |                         ^~~~~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:838:24: note: expanded from macro '__careful_cmp'
  838 |         __builtin_choose_expr(__safe_cmp(x, y), \
      |                               ^~~~~~~~~~~~~~~~
../include/linux/kernel.h:828:4: note: expanded from macro '__safe_cmp'
  828 |                 (__typecheck(x, y) && __no_side_effects(x, y))
      |                  ^~~~~~~~~~~~~~~~~
../include/linux/kernel.h:814:29: note: expanded from macro '__typecheck'
  814 |                 (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
      |                            ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~
../net/ipv4/tcp_bbrplus.c:1163:6: error: field designator 'tso_segs_goal' does not refer to any field in type 'struct tcp_congestion_ops'
 1163 |     .tso_segs_goal  = bbr_tso_segs_goal,
      |     ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.
make[3]: *** [../scripts/Makefile.build:364: net/ipv4/tcp_bbrplus.o] Error 1
make[3]: *** Waiting for unfinished jobs....

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>