qca-wifi-host-cmn: Fix compilation after smxxx0-08300 merge.
drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/wmi/src/wmi_unified_sta_tlv.c:1364:20: error: unused function 'wmi_sar2_result_string' [-Werror,-Wunused-function]
static const char *wmi_sar2_result_string(uint32_t result)
                   ^
1 error generated.

Signed-off-by: Vishalcj17 <vishalcj@aospa.co>
Change-Id: Ida5ad9edf88538c8c7454f6af31e40f160c8985b
[Flopster101: This is actually because disabling debug leaves wmi_debug() unused.]
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>